name: Deploy Docs

on:
    push: 
        branches: 
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '22'
                cache: 'npm'
                cache-dependency-path: '**/package-lock.json'

            - run: npm ci
            - run: npm run build
              env:
                TURBO_TOKEN: ${{secrets.TURBO_TOKEN}}
                TURBO_TEAM: joaoh4547s-projects

            - name: Deploy storybook
              working-directory: ./packages/docs
              run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
              env:
                GH_TOKEN: ${{github.actor}}:${{ secrets.GITHUB_TOKEN }}